random_seed: 42
ckpt_path: null
gpus: "0,1"

# Dataset options:
dataset:
  name: "cv"
  data_root: "/project/shrikann_35/tiantiaf/arts/cv-corpus-11.0-2022-09-21/en/"
  split: "train"

# Dataloader options:
dataloader:
  batch_size: 64
  num_workers: 4
  train_frac: 0.8

# Model options:
lightning:
  model:
    input_dim: 512 
    latent_dim: 64
  optimizer:
    lr: 0.001
    weight_decay: 0.000
  scheduler:
    T_max: 50

pca_batches: 0

# Training options:
trainer:
  max_epochs: 50
  val_check_interval: 1.0 # Must be >= 1 for iterable-type dataset
  log_every_n_steps: 10    
  sync_batchnorm: True
  accelerator: "gpu"
  devices: "auto"
  deterministic: False
  detect_anomaly: False
  accumulate_grad_batches: 1

# Tensorboard options:
tensorboard:
  save_dir: "/home1/nmehlman/arts/pseudo_speakers/logs"
  name: null
  version: null     # Automatic versioning if set to null (recommended)


