random_seed: 42
ckpt_path: null
gpus: "0,1"

# Dataset options:
dataset:
  name: "cv"
  data_root: "/project/shrikann_35/tiantiaf/arts/cv-corpus-11.0-2022-09-21/en/"
  se_model: "vc"
  split: "train"

# Dataloader options:
dataloader:
  batch_size: 1024
  num_workers: 16
  train_frac: 0.9

# Model options:
lightning:
  kl_loss_weight: 0.1
  use_cos_loss: true
  model:
    input_dim: 256 
    latent_dim: 32
    normalize_decoder: true
  optimizer:
    lr: 0.0002
    weight_decay: 0.000
  scheduler:
    T_max: 500

pca_batches: 2

# Training options:
trainer:
  max_epochs: 500
  val_check_interval: 1.0 # Must be >= 1 for iterable-type dataset
  log_every_n_steps: 10    
  num_nodes: 2
  sync_batchnorm: True
  accelerator: "gpu"
  devices: "auto"
  deterministic: False
  detect_anomaly: False
  accumulate_grad_batches: 1

# Tensorboard options:
tensorboard:
  save_dir: "/project/shrikann_35/nmehlman/logs/ps_vae/"
  name: "cv_freevc_01"
  version: null     # Automatic versioning if set to null (recommended)


