random_seed: 42
ckpt_path: null
gpus: "0"

# Dataset options:
dataset:
  data_root: "/project/shrikann_35/tiantiaf/arts/cv-corpus-11.0-2022-09-21/en/"
  split: "train"

# Dataloader options:
dataloader:
  batch_size: 32
  num_workers: 4
  train_frac: 0.8

# Model options:
lightning:
  kl_loss_weight: 2
  model:
    input_dim: 512 
    latent_dim: 16 
  optimizer:
    lr: 0.0005
    weight_decay: 0.000
  scheduler:
    T_max: 10

pca_batches: 16

# Training options:
trainer:
  max_epochs: 10
  val_check_interval: 0.01 # Must be >= 1 for iterable-type dataset
  log_every_n_steps: 10    
  sync_batchnorm: True
  accelerator: "gpu"
  devices: "auto"
  deterministic: False
  detect_anomaly: False
  accumulate_grad_batches: 1

# Tensorboard options:
tensorboard:
  save_dir: "/home1/nmehlman/arts/pseudo_speakers/logs"
  name: "pca_debug"
  version: null     # Automatic versioning if set to null (recommended)


