random_seed: 42
ckpt_path: null
gpus: "0" # DEBUG

# Dataset options:
dataset:
  metadata_transform: "gender"
  data_root: "/project/shrikann_35/tiantiaf/arts/cv-corpus-11.0-2022-09-21/en/"
  split: "train"

# Dataloader options:
dataloader:
  batch_size: 2048
  num_workers: 16
  train_frac: 0.9

# Model options:
lightning:
  kl_loss_weight: 4
  classifier_loss_weight: 1
  model:
    input_dim: 512 
    latent_dim: 16 
  classifier:
    input_dim: 16
    num_classes: 2
    num_layers: 1
  optimizer:
    lr: 0.0002
    weight_decay: 0.000
  scheduler:
    T_max: 300

pca_batches: 2

# Training options:
trainer:
  max_epochs: 1
  num_nodes: 1 # DEBUG
  limit_train_batches: 25 # DEBUG
  limit_val_batches: 25 # DEBUG
  val_check_interval: 0.25 # Must be >= 1 for iterable-type dataset
  log_every_n_steps: 10    
  sync_batchnorm: True
  accelerator: "gpu"
  devices: "auto"
  deterministic: False
  detect_anomaly: False
  accumulate_grad_batches: 1

# Tensorboard options:
tensorboard:
  save_dir: "/project/shrikann_35/nmehlman/logs/ps_vae/"
  name: "debug"
  version: null     # Automatic versioning if set to null (recommended)


