random_seed: 42
ckpt_path: null
gpus: "0,1"

# Dataset options:
dataset:
  name: "vctk"
  data_root: "/project/shrikann_35/nmehlman/psg_data/vctk_embeds"
  split: "train"

# Dataloader options:
dataloader:
  batch_size: 1024
  num_workers: 16
  train_frac: 0.9

# Model options:
lightning:
  model:
    input_dim: 256 
    latent_dim: 16
  optimizer:
    lr: 0.0002
    weight_decay: 0.000
  scheduler:
    T_max: 500

pca_batches: 2

# Training options:
trainer:
  max_epochs: 500
  val_check_interval: 1.0 # Must be >= 1 for iterable-type dataset
  log_every_n_steps: 10    
  sync_batchnorm: True
  accelerator: "gpu"
  devices: "auto"
  deterministic: False
  detect_anomaly: False
  accumulate_grad_batches: 1

# Tensorboard options:
tensorboard:
  save_dir: "/project/shrikann_35/nmehlman/logs/ps_vae/"
  name: "vctk_train_01"
  version: null     # Automatic versioning if set to null (recommended)


